// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXAMyWn02oFPsSRUaIYm7dGhGyl7z89wo',
    appId: '1:182306419468:web:4b9bc279def848099a8f29',
    messagingSenderId: '182306419468',
    projectId: 'mission-test-srv-infotech',
    authDomain: 'mission-test-srv-infotech.firebaseapp.com',
    storageBucket: 'mission-test-srv-infotech.appspot.com',
    measurementId: 'G-82NGQ1RSEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPbntwgutBrhDrH9HhMPBtfWDwrmiVLI',
    appId: '1:182306419468:android:dbd801355df6fd9a9a8f29',
    messagingSenderId: '182306419468',
    projectId: 'mission-test-srv-infotech',
    storageBucket: 'mission-test-srv-infotech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7CwPhNs15fwAH2cRTKkRFxyZRLSEbYo',
    appId: '1:182306419468:ios:d16a43fb18092b519a8f29',
    messagingSenderId: '182306419468',
    projectId: 'mission-test-srv-infotech',
    storageBucket: 'mission-test-srv-infotech.appspot.com',
    iosBundleId: 'com.example.missionTestSvrInfotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7CwPhNs15fwAH2cRTKkRFxyZRLSEbYo',
    appId: '1:182306419468:ios:b3db21849a2ff34e9a8f29',
    messagingSenderId: '182306419468',
    projectId: 'mission-test-srv-infotech',
    storageBucket: 'mission-test-srv-infotech.appspot.com',
    iosBundleId: 'com.example.missionTestSvrInfotech.RunnerTests',
  );
}
